import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CalendarDays, Clock, Car, Users, Truck, Plus } from "lucide-react";
import { dispatchRequest } from "@/components/mover/dispatchApi";
import { usePartnerCompany } from "@/contexts/PartnerCompanyContext";
import { formatDateTime, formatTime, wallClockToUTC } from "@shared/timezone";

export default function MoverCalendar() {
  const { i18n } = useTranslation();
  const es = i18n.language.startsWith("es");
  const { active, can } = usePartnerCompany();
  const timezone = active?.company.operatingTimezone || "America/Mexico_City";
  const qc = useQueryClient();
  const canAvailability = can("availability:manage");
  const [schedule, setSchedule] = useState({ dayOfWeek: "1", startsAt: "08:00", endsAt: "17:00" });
  const [exception, setException] = useState({ date: new Date().toISOString().slice(0, 10), startsAt: "08:00", endsAt: "17:00", kind: "blackout", label: "" });
  const range = useMemo(() => { const from = new Date(); from.setHours(0, 0, 0, 0); const to = new Date(from); to.setDate(to.getDate() + 14); return { from: from.toISOString(), to: to.toISOString() }; }, []);
  const calendar = useQuery({ queryKey: ["partner-calendar", range.from], queryFn: () => dispatchRequest<any>(`/api/partner/dispatch/calendar?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`) });
  const refresh = () => qc.invalidateQueries({ queryKey: ["partner-calendar"] });
  const scheduleMutation = useMutation({ mutationFn: () => dispatchRequest("/api/partner/dispatch/calendar/schedule", { method: "PUT", body: JSON.stringify({ dayOfWeek: Number(schedule.dayOfWeek), startsAt: schedule.startsAt, endsAt: schedule.endsAt, timezone }) }), onSuccess: refresh });
  const exceptionMutation = useMutation({ mutationFn: () => dispatchRequest("/api/partner/dispatch/calendar/exceptions", { method: "POST", body: JSON.stringify({ startsAt: wallClockToUTC(`${exception.date}T${exception.startsAt}`, timezone).toISOString(), endsAt: wallClockToUTC(`${exception.date}T${exception.endsAt}`, timezone).toISOString(), kind: exception.kind, label: exception.label || null, timezone }) }), onSuccess: refresh });
  const submitSchedule = () => { if (schedule.startsAt >= schedule.endsAt) return; scheduleMutation.mutate(); };
  const submitException = () => { if (!exception.date || exception.startsAt >= exception.endsAt) return; exceptionMutation.mutate(); };
  const days = [es ? "Domingo" : "Sunday", es ? "Lunes" : "Monday", es ? "Martes" : "Tuesday", es ? "Miércoles" : "Wednesday", es ? "Jueves" : "Thursday", es ? "Viernes" : "Friday", es ? "Sábado" : "Saturday"];
  const links = [{ href: "/mover/dashboard/drivers", label: es ? "Cuadrillas" : "Crews", icon: Users }, { href: "/mover/dashboard/fleet", label: es ? "Flota" : "Fleet", icon: Car }, { href: "/mover/dashboard/calendar", label: es ? "Calendario operativo" : "Operations calendar", icon: CalendarDays }];
  const data = calendar.data;
  return <DashboardLayout links={links} userType="mover"><div className="mx-auto w-full max-w-6xl space-y-6">
    <div><p className="workspace-kicker">{es ? "Agenda del socio" : "Partner agenda"}</p><h1 className="text-3xl text-[var(--usg-ink)]">{es ? "Calendario operativo" : "Operations calendar"}</h1><p className="text-muted-foreground">{es ? "Disponibilidad, excepciones y servicios asignados en la zona horaria de la empresa." : "Availability, exceptions and assigned services in the company timezone."}</p></div>
    <Card className="border-orange-200/70"><CardContent className="grid gap-4 p-5 sm:grid-cols-3"><div><p className="text-sm text-muted-foreground">{es ? "Zona horaria" : "Time zone"}</p><p className="font-semibold">{timezone}</p></div><div><p className="text-sm text-muted-foreground">{es ? "Buffer de viaje" : "Travel buffer"}</p><p className="font-semibold">{active?.company.travelBufferMinutes ?? 60} min</p></div><div><p className="text-sm text-muted-foreground">{es ? "Buffer entre servicios" : "Turnaround buffer"}</p><p className="font-semibold">{active?.company.turnaroundBufferMinutes ?? 30} min</p></div></CardContent></Card>
    {calendar.isLoading ? <div className="h-64 animate-pulse rounded-xl bg-muted" /> : calendar.isError ? <Card><CardContent className="py-12 text-center text-muted-foreground">{es ? "No se pudo cargar el calendario." : "Calendar could not be loaded."}</CardContent></Card> : <div className="grid gap-6 lg:grid-cols-2">
      <Card><CardHeader><CardTitle><Clock className="mr-2 inline h-5 w-5" />{es ? "Horario recurrente" : "Recurring schedule"}</CardTitle></CardHeader><CardContent className="space-y-2">{data?.schedules?.map((s: any) => <div key={s.id} className="flex justify-between rounded-lg border p-3"><span>{days[s.dayOfWeek]}</span><span>{s.startsAt}–{s.endsAt}</span></div>)}{canAvailability && <div className="grid gap-2 border-t pt-4 sm:grid-cols-4"><select className="h-10 rounded-md border bg-background px-3" value={schedule.dayOfWeek} onChange={(e) => setSchedule({ ...schedule, dayOfWeek: e.target.value })}>{days.map((day, i) => <option value={i} key={day}>{day}</option>)}</select><Input type="time" value={schedule.startsAt} onChange={(e) => setSchedule({ ...schedule, startsAt: e.target.value })} /><Input type="time" value={schedule.endsAt} onChange={(e) => setSchedule({ ...schedule, endsAt: e.target.value })} /><Button onClick={submitSchedule}><Plus className="mr-1 h-4 w-4" />{es ? "Agregar" : "Add"}</Button></div>}</CardContent></Card>
      <Card><CardHeader><CardTitle><CalendarDays className="mr-2 inline h-5 w-5" />{es ? "Excepciones y bloqueos" : "Exceptions & blackouts"}</CardTitle></CardHeader><CardContent className="space-y-2">{data?.exceptions?.map((x: any) => <div key={x.id} className="flex justify-between rounded-lg border p-3"><span>{x.label || x.kind}</span><Badge>{formatDateTime(x.startsAt, { timezone, includeTime: false })}</Badge></div>)}{canAvailability && <div className="grid gap-2 border-t pt-4 sm:grid-cols-2"><Input type="date" value={exception.date} onChange={(e) => setException({ ...exception, date: e.target.value })} /><select className="h-10 rounded-md border bg-background px-3" value={exception.kind} onChange={(e) => setException({ ...exception, kind: e.target.value })}><option value="blackout">{es ? "Bloqueo" : "Blackout"}</option><option value="available">{es ? "Disponible" : "Available"}</option></select><Input type="time" value={exception.startsAt} onChange={(e) => setException({ ...exception, startsAt: e.target.value })} /><Input type="time" value={exception.endsAt} onChange={(e) => setException({ ...exception, endsAt: e.target.value })} /><Input className="sm:col-span-2" placeholder={es ? "Etiqueta opcional" : "Optional label"} value={exception.label} onChange={(e) => setException({ ...exception, label: e.target.value })} /><Button className="sm:col-span-2" onClick={submitException}><Plus className="mr-1 h-4 w-4" />{es ? "Agregar excepción" : "Add exception"}</Button></div>}</CardContent></Card>
      <Card><CardHeader><CardTitle><Car className="mr-2 inline h-5 w-5" />{es ? "Vehículos disponibles" : "Vehicle availability"}</CardTitle></CardHeader><CardContent className="space-y-2">{data?.vehicles?.map((x: any) => <div key={x.window.id} className="rounded-lg border p-3"><p className="font-medium">{x.vehicle.name}</p><p className="text-sm text-muted-foreground">{formatDateTime(x.window.startsAt, { timezone })} — {formatTime(x.window.endsAt, { timezone })}</p></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle><Users className="mr-2 inline h-5 w-5" />{es ? "Cuadrillas disponibles" : "Crew availability"}</CardTitle></CardHeader><CardContent className="space-y-2">{data?.crews?.map((x: any) => <div key={x.window.id} className="rounded-lg border p-3"><p className="font-medium">{x.crew.name}</p><p className="text-sm text-muted-foreground">{formatDateTime(x.window.startsAt, { timezone })} — {formatTime(x.window.endsAt, { timezone })}</p><Badge>{x.window.isAvailable ? (es ? "Disponible" : "Available") : (es ? "No disponible" : "Unavailable")}</Badge></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle><Truck className="mr-2 inline h-5 w-5" />{es ? "Servicios asignados" : "Assigned services"}</CardTitle></CardHeader><CardContent className="space-y-2">{data?.assignments?.map((a: any) => <div key={a.id} className="flex justify-between rounded-lg border p-3"><span>{formatDateTime(a.startsAt, { timezone })}</span><Badge variant="outline">{a.status}</Badge></div>)}</CardContent></Card>
    </div>}
  </div></DashboardLayout>;
}